In [27]:
from obj.stock import stock
import akshare as ak
import pandas as pd

In [2]:
stock_board_industry_name_em_df = ak.stock_board_industry_name_em()
print(stock_board_industry_name_em_df)

0it [00:00, ?it/s]

    排名  板块名称    板块代码       最新价      涨跌额   涨跌幅            总市值   换手率  上涨家数  \
0    1  船舶制造  BK0729   1170.60    73.46  6.70   485621840000  5.67    11
1    2  橡胶制品  BK1018   1660.64    48.64  3.02   321955008000  2.05    26
2    3    电机  BK1030   2417.95    59.44  2.52   259421422000  5.44    26
3    4    游戏  BK1046   1482.29    33.29  2.30   488601744000  5.14    23
4    5  航天航空  BK0480  56547.33  1253.88  2.27  1314739248000  3.66    40
..  ..   ...     ...       ...      ...   ...            ...   ...   ...
81  82  医疗服务  BK0727   1280.96   -11.22 -0.87   831104080000  2.92     7
82  83  生物制品  BK1044   1168.15   -11.76 -1.00  1634900960000  2.69    16
83  84  化学制药  BK0465  40402.47  -480.35 -1.17  2273685344000  4.31    28
84  85  医药商业  BK1042   1153.95   -14.68 -1.26   344650016000  1.75     2
85  86    中药  BK1040   1542.48   -30.07 -1.91   932925008000  3.36     4

    下跌家数  领涨股票  领涨股票-涨跌幅
0      0  国瑞科技     20.00
1      5  华密新材     29.96
2      0  鼎智科技      8.91
3      2  宝通科技      8.99
4      5  恒宇信通     14.94
..   ...   ...       ...
81    36  润达医疗      5.10
82    57   康希诺      6.13
83   119  博瑞医药      9.96
84    28  百洋医药      2.86
85    65   珍宝岛      2.54

[86 rows x 12 columns]

In [7]:
set(list(stock_board_industry_name_em_df["板块名称"]))

{'专业服务',
 '专用设备',
 '中药',
 '互联网服务',
 '交运设备',
 '仪器仪表',
 '保险',
 '光伏设备',
 '光学光电子',
 '公用事业',
 '农牧饲渔',
 '农药兽药',
 '包装材料',
 '化学制品',
 '化学制药',
 '化学原料',
 '化纤行业',
 '化肥行业',
 '医疗器械',
 '医疗服务',
 '医药商业',
 '半导体',
 '商业百货',
 '塑料制品',
 '多元金融',
 '家用轻工',
 '家电行业',
 '小金属',
 '工程咨询服务',
 '工程建设',
 '工程机械',
 '房地产开发',
 '房地产服务',
 '教育',
 '文化传媒',
 '旅游酒店',
 '有色金属',
 '橡胶制品',
 '水泥建材',
 '汽车整车',
 '汽车服务',
 '汽车零部件',
 '消费电子',
 '游戏',
 '煤炭行业',
 '燃气',
 '物流行业',
 '环保行业',
 '玻璃玻纤',
 '珠宝首饰',
 '生物制品',
 '电力行业',
 '电子元件',
 '电子化学品',
 '电机',
 '电池',
 '电源设备',
 '电网设备',
 '石油行业',
 '纺织服装',
 '综合行业',
 '美容护理',
 '能源金属',
 '航天航空',
 '航空机场',
 '航运港口',
 '船舶制造',
 '装修建材',
 '装修装饰',
 '计算机设备',
 '证券',
 '贵金属',
 '贸易行业',
 '软件开发',
 '通信服务',
 '通信设备',
 '通用设备',
 '造纸印刷',
 '酿酒行业',
 '采掘行业',
 '钢铁行业',
 '铁路公路',
 '银行',
 '非金属材料',
 '风电设备',
 '食品饮料'}

In [8]:
# 生物制品
# 医疗器械
# 医疗服务
# 医药商业
stock_board_industry_cons_em_df = ak.stock_board_industry_cons_em(symbol="生物制品")
print(stock_board_industry_cons_em_df)

0it [00:00, ?it/s]

    序号      代码      名称    最新价   涨跌幅   涨跌额     成交量           成交额     振幅     最高  \
0    1  688046    药康生物  17.36  5.79  0.95   71833  1.247678e+08   7.86  17.79
1    2  688185     康希诺  84.22  5.28  4.22   54407  4.556292e+08   8.08  86.48
2    3  300142    沃森生物  13.74  4.97  0.65  975043  1.350761e+09   6.26  14.25
3    4  600645    中源协和  27.22  3.30  0.87  169544  4.646691e+08   5.96  27.98
4    5  688180  君实生物-U  38.84  3.13  1.18  129906  4.980077e+08   4.46  39.25
..  ..     ...     ...    ...   ...   ...     ...           ...    ...    ...
69  70  600211    西藏药业  43.66 -5.48 -2.53  190729  8.409984e+08   4.44  45.30
70  71  688163    赛伦生物  25.80 -5.74 -1.57   51224  1.358650e+08   5.70  27.33
71  72  603590    康辰药业  58.41 -5.79 -3.59   71704  4.305690e+08  10.98  64.00
72  73  300683    海特生物  54.02 -7.10 -4.13   94766  5.262729e+08  12.40  59.87
73  74  300204     舒泰神  50.03 -7.33 -3.96  181915  9.271556e+08   7.46  53.33

       最低     今开     昨收    换手率   市盈率-动态    市净率
0   16.50  16.50  16.41   1.75    59.35   3.36
1   80.02  80.02  80.00   4.74  -451.27   4.25
2   13.43  13.50  13.09   6.25  2076.06   2.33
3   26.41  26.61  26.35   3.62   113.60   3.52
4   37.57  37.82  37.66   1.70   -42.44   7.10
..    ...    ...    ...    ...      ...    ...
69  43.25  44.80  46.19   5.92    13.06   3.64
70  25.77  26.81  27.37  11.54   185.78   2.59
71  57.19  61.67  62.00   4.56    52.30   3.04
72  52.66  57.80  58.15   7.76  -126.90   2.97
73  49.30  51.65  53.99   3.85 -2559.16  25.07

[74 rows x 16 columns]

In [ ]:
# create a data dictionary - ticker - industry - and indusry PE PS PB,

In [2]:
# 
a = stock('bj839729')

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.
Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00']. Returning None.

  0%|          | 0/3 [00:00<?, ?it/s]

In [9]:
a.initialize(defaultRateApproach = True, valuationMethod = "earning", defaultLTGrowth = False, \
                        valuationStage = "three", growthCalcuMethod = "earning", growthCalcuHorizon = 5)

profit is downtrend,  be aware

In [10]:
res = a.FV
print("the fair value is ", res)

valuation method is  earning
valuation stage is  three
first stage growth is  -28.976407921086246
second stage growth is  -28.976407921086246
long term growth is  -28.976407921086246
growth period is  5
starting value is  0.15
required rate of returen is  11.957746106295192
the fair value is  0.26026038805420926

In [15]:
stock_info_bj_name_code_df = ak.stock_info_bj_name_code()
print(stock_info_bj_name_code_df)

  0%|          | 0/14 [00:00<?, ?it/s]

       证券代码  证券简称         总股本        流通股本        上市日期              所属行业   地区  \
0    430017  星昊医药   122288200   121417900  2023-05-31             医药制造业  北京市
1    430047  诺思兰德   274271974   180106427  2020-11-24             医药制造业  北京市
2    430090  同辉信息   199333546   135347400  2021-08-09        软件和信息技术服务业  北京市
3    430139  华岭股份   269507392   260468480  2022-10-28  计算机、通信和其他电子设备制造业  上海市
4    430198  微创光电   161363872    70152938  2020-07-27  计算机、通信和其他电子设备制造业  湖北省
..      ...   ...         ...         ...         ...               ...  ...
264  920445  龙竹科技   146930025   105262791  2020-07-27             家具制造业  福建省
265  920489  佳先股份   136459200    85577249  2020-07-27      化学原料和化学制品制造业  安徽省
266  920682  球冠电缆   324480000   188324422  2020-07-27        电气机械和器材制造业  浙江省
267  920799  艾融软件   209780050   120704571  2020-07-27        软件和信息技术服务业  上海市
268  920819  颖泰生物  1225800000  1207507500  2020-07-27      化学原料和化学制品制造业  北京市

           报告日期
0    2025-07-31
1    2025-07-31
2    2025-07-31
3    2025-07-31
4    2025-07-31
..          ...
264  2025-07-31
265  2025-07-31
266  2025-07-31
267  2025-07-31
268  2025-07-31

[269 rows x 8 columns]

In [35]:
industry = "医药商业"
# potential_list = {}

In [36]:
# potential_list = {}
# runned = set()

In [38]:
### search for stock
# industry = "生物制品"
stock_board_industry_cons_em_df = ak.stock_board_industry_cons_em(symbol=industry)
excludeList = ['688428', '688520', '688235', '603014', '688351']
i = 0
for item in stock_board_industry_cons_em_df.iterrows():
    # print(each[1])
    # print(each[1]["代码"], each[1]["名称"], each[1]["昨收"])
    each = item[1]
    if each["代码"][0] == "4" or each["代码"][0] == "8":
        ticker = "bj" + each["代码"]
    elif each["代码"][0] == "0" or each["代码"][0] == "3":
        ticker = "sz" + each["代码"]
    elif each["代码"][0] == "6":
        ticker = "sh" + each["代码"]
    print(ticker)
    if ticker in runned:
        continue
    else:
        runned.add(ticker)
    if each["市盈率-动态"] > 0 and each["代码"] not in excludeList:
        # print(ticker)
        try:
            a = stock(ticker)
            a.initialize(defaultRateApproach = True, valuationMethod = "earning", defaultLTGrowth = False, \
                                valuationStage = "three", growthCalcuMethod = "earning", growthCalcuHorizon = 5)
        except ValueError:
            print("there is a value error", ValueError)
        if a.firstStageGrowthValue:
            print("----------the current price for ", ticker, " is ", each["昨收"], "-------------------")
            print("----------the fair value for ", ticker, " is ", a.FV, "-------------------")
            if a.FV > each["昨收"]:
                potential_list[ticker] = {}
                potential_list[ticker]["ticker"] = ticker
                potential_list[ticker]["FV"] = a.FV
                potential_list[ticker]["current price"] = each["昨收"]
                potential_list[ticker]["industry"] = industry
        else:
            print("first stage growth is none")
    else:
        print("div not able to pull")
        print("PE is negative which means the stock doesn't have positive earning", each["市盈率-动态"])
    i += 1
    # if i == 10:
    #     break

0it [00:00, ?it/s]

sz301408
sh603716
sz301126

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00', '2013-12-31 00:00:00', '2012-12-31 00:00:00']. Returning None.

  0%|          | 0/3 [00:00<?, ?it/s]

profit is downtrend,  be aware
----------the current price for  sz301126  is  13.48 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -25.59301633391591
second stage growth is  -25.59301633391591
long term growth is  -25.59301633391591
growth period is  5
starting value is  0.13
required rate of returen is  11.636328381311767
----------the fair value for  sz301126  is  0.2598194502369118 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -25.59301633391591
second stage growth is  -25.59301633391591
long term growth is  -25.59301633391591
growth period is  5
starting value is  0.13
required rate of returen is  11.636328381311767
sz300937
sz301015
sh603122
sz002589
sz000950
sh603233
sh600829
sh600713
sh600998
sz301263
sh605266
sz002788
sh600056
sh603368
sz002727
sh600833
sh601607
sz000411
sh603939
sh600272

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/7 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00', '2013-12-31 00:00:00', '2012-12-31 00:00:00', '2011-12-31 00:00:00', '2010-12-31 00:00:00', '2009-12-31 00:00:00', '2008-12-31 00:00:00', '2007-12-31 00:00:00', '2006-12-31 00:00:00', '2005-12-31 00:00:00', '2004-12-31 00:00:00', '2003-12-31 00:00:00', '2002-12-31 00:00:00', '2001-12-31 00:00:00', '2000-12-31 00:00:00', '1999-12-31 00:00:00', '1998-12-31 00:00:00', '1997-12-31 00:00:00', '1996-12-31 00:00:00', '1995-12-31 00:00:00', '1994-12-31 00:00:00', '1993-12-31 00:00:00']. Returning None.

  0%|          | 0/6 [00:00<?, ?it/s]

----------the current price for  sh600272  is  14.19 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  9.238846414037315
second stage growth is  5
long term growth is  5
growth period is  5
starting value is  0.14
required rate of returen is  12.14129006840506
----------the fair value for  sh600272  is  2.45299134545073 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  9.238846414037315
second stage growth is  5
long term growth is  5
growth period is  5
starting value is  0.14
required rate of returen is  12.14129006840506
sh600511
sz002462

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00', '2013-12-31 00:00:00', '2012-12-31 00:00:00', '2011-12-31 00:00:00', '2010-12-31 00:00:00', '2009-12-31 00:00:00', '2008-12-31 00:00:00', '2007-12-31 00:00:00']. Returning None.

  0%|          | 0/4 [00:00<?, ?it/s]

profit is downtrend,  be aware
----------the current price for  sz002462  is  14.94 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -17.51024010768655
second stage growth is  -17.51024010768655
long term growth is  -17.51024010768655
growth period is  5
starting value is  0.55
required rate of returen is  10.574284050927277
----------the fair value for  sz002462  is  1.6154579541578995 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -17.51024010768655
second stage growth is  -17.51024010768655
long term growth is  -17.51024010768655
growth period is  5
starting value is  0.55
required rate of returen is  10.574284050927277
sz000028

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00', '2013-12-31 00:00:00', '2012-12-31 00:00:00', '2011-12-31 00:00:00', '2010-12-31 00:00:00', '2009-12-31 00:00:00', '2008-12-31 00:00:00', '2007-12-31 00:00:00', '2006-12-31 00:00:00', '2005-12-31 00:00:00', '2004-12-31 00:00:00', '2003-12-31 00:00:00', '2002-12-31 00:00:00', '2001-12-31 00:00:00', '2000-12-31 00:00:00', '1999-12-31 00:00:00', '1998-12-31 00:00:00', '1997-12-31 00:00:00', '1996-12-31 00:00:00', '1995-12-31 00:00:00', '1994-12-31 00:00:00', '1993-12-31 00:00:00', '1992-12-31 00:00:00', '1991-12-31 00:00:00', '1990-12-31 00:00:00', '1989-12-31 00:00:00']. Returning None.

  0%|          | 0/6 [00:00<?, ?it/s]

profit is downtrend,  be aware
----------the current price for  sz000028  is  25.67 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -17.228423721501617
second stage growth is  -17.228423721501617
long term growth is  -17.228423721501617
growth period is  5
starting value is  1.15
required rate of returen is  5.077889367776366
----------the fair value for  sz000028  is  4.267281300109923 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -17.228423721501617
second stage growth is  -17.228423721501617
long term growth is  -17.228423721501617
growth period is  5
starting value is  1.15
required rate of returen is  5.077889367776366
sh603883

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00', '2013-12-31 00:00:00', '2012-12-31 00:00:00', '2011-12-31 00:00:00']. Returning None.

  0%|          | 0/3 [00:00<?, ?it/s]

profit is downtrend,  be aware
----------the current price for  sh603883  is  18.7 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -11.744650659599277
second stage growth is  -11.744650659599277
long term growth is  -11.744650659599277
growth period is  5
starting value is  0.68
required rate of returen is  9.250552782709955
----------the fair value for  sh603883  is  2.8584451546934697 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -11.744650659599277
second stage growth is  -11.744650659599277
long term growth is  -11.744650659599277
growth period is  5
starting value is  0.68
required rate of returen is  9.250552782709955
sz000705

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/7 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00', '2013-12-31 00:00:00', '2012-12-31 00:00:00', '2011-12-31 00:00:00', '2010-12-31 00:00:00', '2009-12-31 00:00:00', '2008-12-31 00:00:00', '2007-12-31 00:00:00', '2006-12-31 00:00:00', '2005-12-31 00:00:00', '2004-12-31 00:00:00', '2003-12-31 00:00:00', '2002-12-31 00:00:00', '2001-12-31 00:00:00', '2000-12-31 00:00:00', '1999-12-31 00:00:00', '1998-12-31 00:00:00', '1997-12-31 00:00:00', '1996-12-31 00:00:00', '1995-12-31 00:00:00', '1994-12-31 00:00:00', '1993-12-31 00:00:00']. Returning None.

  0%|          | 0/6 [00:00<?, ?it/s]

profit is downtrend,  be aware
----------the current price for  sz000705  is  9.46 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -30.79588962733002
second stage growth is  -30.79588962733002
long term growth is  -30.79588962733002
growth period is  5
starting value is  0.1
required rate of returen is  10.653472700809075
----------the fair value for  sz000705  is  0.16696061527993347 -------------------
valuation method is  earning
valuation stage is  three
first stage growth is  -30.79588962733002
second stage growth is  -30.79588962733002
long term growth is  -30.79588962733002
growth period is  5
starting value is  0.1
required rate of returen is  10.653472700809075
sz000705
sz301017

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00', '2013-12-31 00:00:00']. Returning None.

  0%|          | 0/3 [00:00<?, ?it/s]

there is a value error <class 'ValueError'>
first stage growth is none
sz000078

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00', '2013-12-31 00:00:00', '2012-12-31 00:00:00', '2011-12-31 00:00:00', '2010-12-31 00:00:00', '2009-12-31 00:00:00', '2008-12-31 00:00:00', '2007-12-31 00:00:00', '2006-12-31 00:00:00', '2005-12-31 00:00:00', '2004-12-31 00:00:00', '2003-12-31 00:00:00', '2002-12-31 00:00:00', '2001-12-31 00:00:00', '2000-12-31 00:00:00', '1999-12-31 00:00:00', '1998-12-31 00:00:00', '1997-12-31 00:00:00', '1996-12-31 00:00:00', '1995-12-31 00:00:00']. Returning None.

  0%|          | 0/6 [00:00<?, ?it/s]

there is a value error <class 'ValueError'>
first stage growth is none

In [39]:
potential_list

{'bj832982': {'ticker': 'bj832982',
  'FV': 1519.042818069919,
  'current price': 325.35,
  'industry': '生物制品'},
 'sz000403': {'ticker': 'sz000403',
  'FV': 56.73081338295862,
  'current price': 18.43,
  'industry': '生物制品'},
 'sh688710': {'ticker': 'sh688710',
  'FV': 56.73081338295862,
  'current price': 42.51,
  'industry': '生物制品'},
 'sz301301': {'ticker': 'sz301301',
  'FV': 273.7392252577139,
  'current price': 12.55,
  'industry': '生物制品'},
 'sh688278': {'ticker': 'sh688278',
  'FV': 577.7751122705808,
  'current price': 88.4,
  'industry': '生物制品'},
 'sz000534': {'ticker': 'sz000534',
  'FV': 19.356504982494076,
  'current price': 16.8,
  'industry': '生物制品'},
 'sz300009': {'ticker': 'sz300009',
  'FV': 26.298551071888326,
  'current price': 11.53,
  'industry': '生物制品'},
 'sh600211': {'ticker': 'sh600211',
  'FV': 60.37182925568682,
  'current price': 43.88,
  'industry': '生物制品'},
 'sh688606': {'ticker': 'sh688606',
  'FV': 108.61832073932393,
  'current price': 73.42,
  'industry': '医疗器械'},
 'sh688389': {'ticker': 'sh688389',
  'FV': 24.405381671549144,
  'current price': 13.88,
  'industry': '医疗器械'},
 'sz300677': {'ticker': 'sz300677',
  'FV': 148.6422404162851,
  'current price': 37.7,
  'industry': '医疗器械'},
 'sz300760': {'ticker': 'sz300760',
  'FV': 435.73906846826725,
  'current price': 228.03,
  'industry': '医疗器械'},
 'sh688767': {'ticker': 'sh688767',
  'FV': 132.94765958346653,
  'current price': 32.51,
  'industry': '医疗器械'},
 'sz002223': {'ticker': 'sz002223',
  'FV': 82.13018735427843,
  'current price': 35.18,
  'industry': '医疗器械'},
 'sz002432': {'ticker': 'sz002432',
  'FV': 2423.0376938218683,
  'current price': 39.09,
  'industry': '医疗器械'},
 'sh688139': {'ticker': 'sh688139',
  'FV': 2423.0376938218683,
  'current price': 33.79,
  'industry': '医疗器械'},
 'sh600529': {'ticker': 'sh600529',
  'FV': 49.98305713327089,
  'current price': 22.91,
  'industry': '医疗器械'},
 'sh688617': {'ticker': 'sh688617',
  'FV': 619.3931737652294,
  'current price': 282.88,
  'industry': '医疗器械'},
 'sh688289': {'ticker': 'sh688289',
  'FV': 23.411939160012853,
  'current price': 22.34,
  'industry': '医疗器械'},
 'sh603718': {'ticker': 'sh603718',
  'FV': 78.22556186276523,
  'current price': 7.67,
  'industry': '医疗器械'},
 'sh603301': {'ticker': 'sh603301',
  'FV': 33.126224107862555,
  'current price': 22.37,
  'industry': '医疗器械'},
 'sh603259': {'ticker': 'sh603259',
  'FV': 262.6658524724905,
  'current price': 93.58,
  'industry': '医疗服务'},
 'sz301015': {'ticker': 'sz301015',
  'FV': 41.95933055276319,
  'current price': 23.77,
  'industry': '医药商业'},
 'sh600713': {'ticker': 'sh600713',
  'FV': 9.454729986957613,
  'current price': 5.21,
  'industry': '医药商业'},
 'sh603368': {'ticker': 'sh603368',
  'FV': 45.60456979835056,
  'current price': 18.33,
  'industry': '医药商业'},
 'sh600833': {'ticker': 'sh600833',
  'FV': 39.75192724142985,
  'current price': 13.33,
  'industry': '医药商业'},
 'sz002788': {'ticker': 'sz002788',
  'FV': 18.519678010315005,
  'current price': 8.6,
  'industry': '医药商业'},
 'sh600511': {'ticker': 'sh600511',
  'FV': 55.52027259863276,
  'current price': 29.88,
  'industry': '医药商业'},
 'sz000411': {'ticker': 'sz000411',
  'FV': 25.53046753976944,
  'current price': 11.2,
  'industry': '医药商业'}}

In [40]:
res = pd.DataFrame.from_dict(potential_list, orient='index')
res.index.name = '代码'
res

            ticker           FV  current price industry
代码
bj832982  bj832982  1519.042818         325.35     生物制品
sz000403  sz000403    56.730813          18.43     生物制品
sh688710  sh688710    56.730813          42.51     生物制品
sz301301  sz301301   273.739225          12.55     生物制品
sh688278  sh688278   577.775112          88.40     生物制品
sz000534  sz000534    19.356505          16.80     生物制品
sz300009  sz300009    26.298551          11.53     生物制品
sh600211  sh600211    60.371829          43.88     生物制品
sh688606  sh688606   108.618321          73.42     医疗器械
sh688389  sh688389    24.405382          13.88     医疗器械
sz300677  sz300677   148.642240          37.70     医疗器械
sz300760  sz300760   435.739068         228.03     医疗器械
sh688767  sh688767   132.947660          32.51     医疗器械
sz002223  sz002223    82.130187          35.18     医疗器械
sz002432  sz002432  2423.037694          39.09     医疗器械
sh688139  sh688139  2423.037694          33.79     医疗器械
sh600529  sh600529    49.983057          22.91     医疗器械
sh688617  sh688617   619.393174         282.88     医疗器械
sh688289  sh688289    23.411939          22.34     医疗器械
sh603718  sh603718    78.225562           7.67     医疗器械
sh603301  sh603301    33.126224          22.37     医疗器械
sh603259  sh603259   262.665852          93.58     医疗服务
sz301015  sz301015    41.959331          23.77     医药商业
sh600713  sh600713     9.454730           5.21     医药商业
sh603368  sh603368    45.604570          18.33     医药商业
sh600833  sh600833    39.751927          13.33     医药商业
sz002788  sz002788    18.519678           8.60     医药商业
sh600511  sh600511    55.520273          29.88     医药商业
sz000411  sz000411    25.530468          11.20     医药商业

In [41]:
res.to_csv("医疗股票_v1.csv")

In [11]:
a.incomest.eps

2024-12-31 00:00:00    0.27
2023-12-31 00:00:00    0.39
2022-12-31 00:00:00    0.42
2021-12-31 00:00:00    0.35
2020-12-31 00:00:00    0.21
2019-12-31 00:00:00     NaN
2018-12-31 00:00:00     NaN
dtype: float64

In [10]:
stock_board_industry_cons_em_df

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,最低,今开,昨收,换手率,市盈率-动态,市净率
0,1,688046,药康生物,17.35,5.73,0.94,71841,1.247817e+08,7.86,17.79,16.50,16.50,16.41,1.75,59.32,3.36
1,2,688185,康希诺,84.21,5.26,4.21,54412,4.556717e+08,8.08,86.48,80.02,80.02,80.00,4.74,-451.21,4.25
2,3,300142,沃森生物,13.74,4.97,0.65,975472,1.351350e+09,6.26,14.25,13.43,13.50,13.09,6.26,2076.06,2.33
3,4,600645,中源协和,27.22,3.30,0.87,169549,4.646827e+08,5.96,27.98,26.41,26.61,26.35,3.62,113.60,3.52
4,5,688180,君实生物-U,38.86,3.19,1.20,130166,4.990162e+08,4.46,39.25,37.57,37.82,37.66,1.70,-42.47,7.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,70,600211,西藏药业,43.66,-5.48,-2.53,190795,8.412865e+08,4.44,45.30,43.25,44.80,46.19,5.92,13.06,3.64
70,71,688163,赛伦生物,25.82,-5.66,-1.55,51236,1.358960e+08,5.70,27.33,25.77,26.81,27.37,11.55,185.92,2.59
71,72,603590,康辰药业,58.35,-5.89,-3.65,71716,4.306390e+08,10.98,64.00,57.19,61.67,62.00,4.56,52.24,3.04
72,73,300683,海特生物,54.02,-7.10,-4.13,94788,5.263918e+08,12.40,59.87,52.66,57.80,58.15,7.77,-126.90,2.97
73,74,300204,舒泰神,50.00,-7.39,-3.99,181976,9.274607e+08,7.46,53.33,49.30,51.65,53.99,3.86,-2557.63,25.06

In [ ]:
# a = stock('sh688428')

In [11]:
a = stock('sz300009')

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

Warning: ASSET_DISPOSAl_INCOME not found in data for key ['2024-12-31 00:00:00', '2023-12-31 00:00:00', '2022-12-31 00:00:00', '2021-12-31 00:00:00', '2020-12-31 00:00:00', '2019-12-31 00:00:00', '2018-12-31 00:00:00', '2017-12-31 00:00:00', '2016-12-31 00:00:00', '2015-12-31 00:00:00', '2014-12-31 00:00:00', '2013-12-31 00:00:00', '2012-12-31 00:00:00', '2011-12-31 00:00:00', '2010-12-31 00:00:00', '2009-12-31 00:00:00', '2008-12-31 00:00:00', '2007-12-31 00:00:00', '2006-12-31 00:00:00']. Returning None.

  0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
# df = ak.stock_dividend_cninfo('688520')
# df

In [24]:
from datetime import datetime
def func(x):
    if x["报告时间"]:
        return datetime(int(x["报告时间"][0:4]), 12, 31)
    else: # if 报告时间 is None
        return datetime(int(x["实施方案公告日期"].year), 12, 31) 
df["date"] = df.apply(lambda x: func(x), axis=1) 
df

,实施方案公告日期,分红类型,送股比例,转增比例,派息比例,股权登记日,除权日,派息日,股份到账日,实施方案分红说明,报告时间,date
0,1994-04-18,年度分红,5.00,1.0,1.0,1994-04-26,1994-04-27,NaT,None,10送1转增5股派1元,1993年报,1993-12-31
1,1995-06-20,年度分红,0.00,1.0,1.0,1995-06-26,1995-06-27,NaT,None,"个人股10送1股派1元;国家股,法人股:10派2元",1994年报,1994-12-31
2,1996-07-02,年度分红,0.00,1.0,1.0,1996-07-09,1996-07-10,1996-07-12,None,10送1股派1.00元,1995年报,1995-12-31
3,1997-07-11,年度分红,0.00,0.0,1.6,1997-07-21,1997-07-22,NaT,None,10派1.60元(含税),1996年报,1996-12-31
4,1998-07-03,年度分红,1.00,0.0,1.0,1998-07-10,1998-07-13,1998-07-17,None,10转增1股派1元(含税),1997年报,1997-12-31
5,2001-07-03,年度分红,NaN,NaN,1.0,2001-07-09,2001-07-10,2001-07-11,None,10派1元（含税）,2000年报,2000-12-31
6,2004-06-16,年度分红,0.00,0.0,1.0,2004-06-22,2004-06-23,2004-06-23,None,10派1元(含税),2003年报,2003-12-31
7,2006-08-09,股改分红,5.31,NaN,NaN,2006-08-10,NaT,NaT,None,10转增5.31股,None,2006-12-31
8,2008-07-03,年度分红,NaN,NaN,1.0,2008-07-10,2008-07-11,2008-07-11,None,10派1元（含税）,2007年报,2007-12-31
9,2009-06-16,年度分红,NaN,NaN,0.5,2009-06-19,2009-06-22,2009-06-22,None,10派0.5元（含税）,2008年报,2008-12-31
10,2010-05-14,年度分红,NaN,NaN,1.5,2010-05-20,2010-05-21,2010-05-21,None,10派1.5元（含税）,2009年报,2009-12-31
11,2011-08-20,年度分红,NaN,NaN,1.0,2011-08-25,2011-08-26,2011-08-26,None,10派1元(含税),2010年报,2010-12-31
12,2012-08-17,年度分红,NaN,NaN,0.5,2012-08-23,2012-08-24,2012-08-24,None,10派0.5元(含税),2011年报,2011-12-31
13,2013-08-03,年度分红,NaN,NaN,0.5,2013-08-08,2013-08-09,2013-08-09,None,10派0.5元(含税),2012年报,2012-12-31
14,2014-12-05,中期分红,NaN,NaN,1.0,2014-12-10,2014-12-11,2014-12-11,None,10派1元(含税),2014半年报,2014-12-31
15,2015-05-12,年度分红,NaN,NaN,0.5,2015-05-18,2015-05-19,2015-05-19,None,10派0.5元(含税),2014年报,2014-12-31
16,2016-05-31,年度分红,NaN,NaN,0.5,2016-06-07,2016-06-08,2016-06-08,None,10派0.5元(含税),2015年报,2015-12-31
17,2017-06-16,年度分红,NaN,NaN,0.5,2017-06-21,2017-06-22,2017-06-22,None,10派0.5元(含税),2016年报,2016-12-31
18,2018-07-14,年度分红,NaN,NaN,0.5,2018-07-19,2018-07-20,2018-07-20,None,10派0.5元(含税),2017年报,2017-12-31
19,2019-07-09,年度分红,NaN,NaN,0.5,2019-07-15,2019-07-16,2019-07-16,None,10派0.5元(含税),2018年报,2018-12-31
20,2020-08-21,年度分红,NaN,NaN,0.5,2020-08-26,2020-08-27,2020-08-27,None,10派0.5元(含税),2019年报,2019-12-31
21,2021-08-20,年度分红,NaN,NaN,0.6,2021-08-26,2021-08-27,2021-08-27,None,10派0.6元(含税),2020年报,2020-12-31
22,2022-08-20,年度分红,NaN,NaN,0.5,2022-08-26,2022-08-29,2022-08-29,None,10派0.5元(含税),2021年报,2021-12-31
23,2023-08-22,年度分红,NaN,NaN,0.5,2023-08-28,2023-08-29,2023-08-29,None,10派0.5元(含税),2022年报,2022-12-31
24,2024-08-20,年度分红,NaN,NaN,1.2,2024-08-26,2024-08-27,2024-08-27,None,10派1.2元(含税),2023年报,2023-12-31

In [6]:
ak.stock_dividend_cninfo('688428')

KeyError: '实施方案公告日期'